# This job runs a schema check for the staging and current variants
name: Run schema checks

# It runs for every PR opened, updated and edited
on:
  pull_request:
    types: [opened, synchronize, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  schema_checks:
    name: Run schema checks
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/environments
    environment: apollo

    # https://docs.github.com/en/actions/reference/encrypted-secrets
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
      GRAPH_REF: flyby-lab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.1.0 | sh
          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Run locations schema check against prod
        run: |
          rover subgraph check ${GRAPH_REF}@current --schema ./subgraph-locations/locations.graphql --name locations
      #- name: Run activities schema check against prod
        # run: |
        #   rover subgraph check ${GRAPH_REF}@current --schema ./subgraph-activities/activities.graphql --name activities
      - name: Run reviews schema check against prod
        run: |
          rover subgraph check ${GRAPH_REF}@current --schema ./subgraph-reviews/reviews.graphql --name reviews